// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gs2c.proto

#include "gs2c.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
class GS2C_ON_LOGIN_RSPDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GS2C_ON_LOGIN_RSP> _instance;
} _GS2C_ON_LOGIN_RSP_default_instance_;
static void InitDefaultsscc_info_GS2C_ON_LOGIN_RSP_gs2c_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_GS2C_ON_LOGIN_RSP_default_instance_;
    new (ptr) ::GS2C_ON_LOGIN_RSP();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::GS2C_ON_LOGIN_RSP::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GS2C_ON_LOGIN_RSP_gs2c_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_GS2C_ON_LOGIN_RSP_gs2c_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_gs2c_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_gs2c_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_gs2c_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_gs2c_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GS2C_ON_LOGIN_RSP, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::GS2C_ON_LOGIN_RSP, field_handleid_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::GS2C_ON_LOGIN_RSP)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_GS2C_ON_LOGIN_RSP_default_instance_),
};

const char descriptor_table_protodef_gs2c_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\ngs2c.proto\"+\n\021GS2C_ON_LOGIN_RSP\022\026\n\016Fie"
  "ld_HandleID\030\001 \001(\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_gs2c_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_gs2c_2eproto_sccs[1] = {
  &scc_info_GS2C_ON_LOGIN_RSP_gs2c_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_gs2c_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gs2c_2eproto = {
  false, false, descriptor_table_protodef_gs2c_2eproto, "gs2c.proto", 65,
  &descriptor_table_gs2c_2eproto_once, descriptor_table_gs2c_2eproto_sccs, descriptor_table_gs2c_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_gs2c_2eproto::offsets,
  file_level_metadata_gs2c_2eproto, 1, file_level_enum_descriptors_gs2c_2eproto, file_level_service_descriptors_gs2c_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gs2c_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_gs2c_2eproto)), true);

// ===================================================================

void GS2C_ON_LOGIN_RSP::InitAsDefaultInstance() {
}
class GS2C_ON_LOGIN_RSP::_Internal {
 public:
};

GS2C_ON_LOGIN_RSP::GS2C_ON_LOGIN_RSP(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:GS2C_ON_LOGIN_RSP)
}
GS2C_ON_LOGIN_RSP::GS2C_ON_LOGIN_RSP(const GS2C_ON_LOGIN_RSP& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  field_handleid_ = from.field_handleid_;
  // @@protoc_insertion_point(copy_constructor:GS2C_ON_LOGIN_RSP)
}

void GS2C_ON_LOGIN_RSP::SharedCtor() {
  field_handleid_ = 0;
}

GS2C_ON_LOGIN_RSP::~GS2C_ON_LOGIN_RSP() {
  // @@protoc_insertion_point(destructor:GS2C_ON_LOGIN_RSP)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GS2C_ON_LOGIN_RSP::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GS2C_ON_LOGIN_RSP::ArenaDtor(void* object) {
  GS2C_ON_LOGIN_RSP* _this = reinterpret_cast< GS2C_ON_LOGIN_RSP* >(object);
  (void)_this;
}
void GS2C_ON_LOGIN_RSP::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GS2C_ON_LOGIN_RSP::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GS2C_ON_LOGIN_RSP& GS2C_ON_LOGIN_RSP::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GS2C_ON_LOGIN_RSP_gs2c_2eproto.base);
  return *internal_default_instance();
}


void GS2C_ON_LOGIN_RSP::Clear() {
// @@protoc_insertion_point(message_clear_start:GS2C_ON_LOGIN_RSP)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  field_handleid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GS2C_ON_LOGIN_RSP::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 Field_HandleID = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          field_handleid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GS2C_ON_LOGIN_RSP::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GS2C_ON_LOGIN_RSP)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 Field_HandleID = 1;
  if (this->field_handleid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_field_handleid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GS2C_ON_LOGIN_RSP)
  return target;
}

size_t GS2C_ON_LOGIN_RSP::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GS2C_ON_LOGIN_RSP)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 Field_HandleID = 1;
  if (this->field_handleid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_field_handleid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GS2C_ON_LOGIN_RSP::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:GS2C_ON_LOGIN_RSP)
  GOOGLE_DCHECK_NE(&from, this);
  const GS2C_ON_LOGIN_RSP* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GS2C_ON_LOGIN_RSP>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:GS2C_ON_LOGIN_RSP)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:GS2C_ON_LOGIN_RSP)
    MergeFrom(*source);
  }
}

void GS2C_ON_LOGIN_RSP::MergeFrom(const GS2C_ON_LOGIN_RSP& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:GS2C_ON_LOGIN_RSP)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.field_handleid() != 0) {
    _internal_set_field_handleid(from._internal_field_handleid());
  }
}

void GS2C_ON_LOGIN_RSP::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:GS2C_ON_LOGIN_RSP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GS2C_ON_LOGIN_RSP::CopyFrom(const GS2C_ON_LOGIN_RSP& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GS2C_ON_LOGIN_RSP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GS2C_ON_LOGIN_RSP::IsInitialized() const {
  return true;
}

void GS2C_ON_LOGIN_RSP::InternalSwap(GS2C_ON_LOGIN_RSP* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(field_handleid_, other->field_handleid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GS2C_ON_LOGIN_RSP::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GS2C_ON_LOGIN_RSP* Arena::CreateMaybeMessage< ::GS2C_ON_LOGIN_RSP >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GS2C_ON_LOGIN_RSP >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
