@startuml Cluster类图
!include Network.puml

class RpcServer {

}

class RpcClient {

}

class Registery {

}

class S2RConnection {}
class R2SConnection {}
class C2RConnection {}
class R2CConnection {}
class C2SConnection {}
class S2CConnection {}

Connection <|-- S2RConnection

Connection <|-- R2SConnection

Connection <|-- C2RConnection

Connection <|-- R2CConnection

Connection <|-- 

'RpcServer 继承于 TcpServer'
TcpServer <|-- RpcServer

'RpcClient 继承于 TcpClient'
TcpClient <|-- RpcClient

'RpcServer 包含多个R2C'

@enduml